language: node_js
addons:
    code_climate:
        repo_token: e6ba3f4984df88142d087efa5d986ccd900ce4a00218a8acef1ac85bf10897df
node_js:
  - stable

script: make lint test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
